=== DavSladk/MUL/slides.dtd
<!ELEMENT slides (slide+)>
<!ELEMENT slide (slideClass|text|button|image|audio|video)*>
<!ELEMENT slideClass (#PCDATA)>

<!ELEMENT text (textClass*,value)>
<!ELEMENT textClass (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!ELEMENT button (buttonClass*,to,value)>
<!ELEMENT buttonClass (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!ELEMENT image (imageClass*,src)>
<!ELEMENT imageClass (#PCDATA)>
<!ELEMENT src (#PCDATA)>

<!ELEMENT audio (audioClass*,src)>
<!ELEMENT audioClass (#PCDATA)>
<!ELEMENT src (#PCDATA)>

<!ELEMENT video (videoClass*,src)>
<!ELEMENT viodeClass (#PCDATA)>
<!ELEMENT src (#PCDATA)>

=== DavSladk/MUL/slides.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE slides SYSTEM "slides.dtd">

<slides>

<!-- slide 0 - postel -->
<slide>

    <slideClass>slide0</slideClass>

    <button>
        <buttonClass>examle</buttonClass>
        <to>2</to>
        <value>Vstanu.</value>
    </button>

    <button>
        <buttonClass>examle</buttonClass>
        <to>1</to>
        <value>Zůstanu v posteli.</value>
    </button>

    <text>
        <textClass>examle</textClass>
        <value>Je ráno. Další nádherný den plný dobrodružství! Co uděláš jako první?</value>
    </text>

    <audio>
        <audioClass>examle</audioClass>
        <src>snoring.mp3</src>
    </audio>

    <image>
        <imageClass>examle</imageClass>
        <src>bed.jpg</src>
    </image>

</slide>

<!-- slide 1 - you win -->
<slide>

    <slideClass>slide1</slideClass>

    <image>
        <imageClass>example</imageClass>
        <src>youwin.png</src>
    </image>

    <audio>
        <audioClass>examle</audioClass>
        <src>fireworks.mp3</src>
    </audio>

    <button>
        <buttonClass>examle</buttonClass>
        <to>0</to>
        <value>Restart</value>
    </button>

</slide>

<!-- slide 2 - v domě -->
<slide>

    <slideClass>slide2</slideClass>

    <button>
        <buttonClass>examle</buttonClass>
        <to>3</to>
        <value>Vyjdu ze dveří.</value>
    </button>

    <button>
        <buttonClass>examle</buttonClass>
        <to>1</to>
        <value>Vrátím se do postele.</value>
    </button>

    <text>
        <textClass>examle</textClass>
        <value>Tvůj nádherný dům. Má vše, co potřebuješ: dveře a postel. Co uděláš?</value>
    </text>

    <image>
        <imageClass>examle</imageClass>
        <src>room.jpg</src>
    </image>

</slide>

<!-- slide 3 - Rozcestí -->
<slide>

    <slideClass>slide3</slideClass>

    <button>
        <buttonClass>examle</buttonClass>
        <to>6</to>
        <value>Do školy.</value>
    </button>

    <button>
        <buttonClass>examle</buttonClass>
        <to>4</to>
        <value>Do lesa.</value>
    </button>

    <button>
        <buttonClass>examle</buttonClass>
        <to>2</to>
        <value>Domů.</value>
    </button>

    <text>
        <textClass>examle</textClass>
        <value>Vyšel jsi z domu a prašnou cestou jsi došel až na rozcestí. Kam se vydáš?</value>
    </text>

    <image>
        <imageClass>examle</imageClass>
        <src>crossroad.png</src>
    </image>

</slide>

</slides>
